### ISSUE TITLE
HADashboard Visualization

### ISSUE THREAD

**Issue by Wachiwi** [harpoonhq/home-assistant-project#15]
@matthiasmoerz want to have the possibility to control Home Assistant Devices with a Dashboard. The Dashboard should support both, PC and mobile device (Tablet, Smartphone). Therefore we want to integrate the [HADashboard](https://home-assistant.io/docs/ecosystem/hadashboard/installation/) into our Gateway.

**Blockers**:

*None*

**Subtasks**:

- Installing the HADashboard
- Starting the HADashboard automoatically in the background after reboot
- Integrate devices

**Acceptance criterias**:
- [x] The HADashboard starts after reboot automatically in the background
- [ ] Integrated devices has been configured for the HADashboard

**Comment by shoesch** [comment]
@tfresh1 did already first appointments on installing the HADashboard on the Raspberry Pi3 and started a Documentation (see [Wiki: HADashboard](https://github.com/harpoonhq/home-assistant-project/wiki/HA-Dashboard))

After reviewing this on a RPi 2, I was faced with two main problems:
- [ ] While trying to run `sudo bundle`, I get an error that I have to use a ruby version >= 1.9.3 (but the installed ruby version is 2.4)
- [ ] After running `dashing start` I get following errors:
```pi@hassbian:~/hadashboard $ dashing start
/home/pi/hadashboard/jobs/homeassistant.rb:7:in `<top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing/app.rb:171:in `block in require_glob'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `each'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing/app.rb:170:in `require_glob'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing/app.rb:181:in `<top (required)>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/bin/thin:23:in `load'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/bin/thin:23:in `<main>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
        from /home/pi/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by shoesch** [comment]
The above problem was solved in a few steps:

1. Make sure, you have a ruby version >= 2.0 installed
    If **not**, install the Ruby Version Manager (RVM) and install a version >= 2.0

2. Don't run `gem install dashing` and `bundle` as root ([Wiki](https://github.com/harpoonhq/home-assistant-project/wiki/HA-Dashboard) has been updated)

3. The copy path of the Wiki `cp lib/ha_conf.rb.example ha_conf.rb` was wrong ([Wiki](https://github.com/harpoonhq/home-assistant-project/wiki/HA-Dashboard) has been updated)

**Comment by shoesch** [comment]
The Dashboard can now be installed. The next step is, to start the HA Dashboard automatically after startup.

**Start HA Dashboard automatically after startup**
The script (which starts the Dashboard), runs manually without any problems. But when trying to start it with `/etc/rc.local` or `cron`, I get following error:
```bash
/usr/bin/env: ruby_executable_hooks: No such file or directory
```

**Comment by shoesch** [comment]
The issue  depends on the RVM - so I have to remove them with all dependencies. So I build hassbian from beginning with the image to have a clean installation working.

After that, I tried to install the HADashboard again - but with the same problem:
I have installed the ruby version 2.1.5, but the 'bundler' says I have installed a ruby version < 1.9.3, so that the Gemfiles couldn't be configured.

**Comment by shoesch** [comment]
To solve the problem, I installed `Docker` and used the Docker Image of the HADashboard. That works like a charm.

I also updated the Wiki entry: [HADashboard](https://github.com/harpoonhq/home-assistant-project/wiki/HADashboard)
