### ISSUE TITLE
DIY HUE Bridge w/o Deconz (Main thread)

### ISSUE THREAD

**Issue by Wachiwi** [harpoonhq/home-assistant-project#2]
As @matthiasmoerz  I don't want to need an additional Phillips Hue Bridge for all my smart bulbs/lamps. I want only one hardware component that allows me to control all my different smart home devices. This should be achieved with the help of the already existing RaspBee module.

**Blockers**:

*This task is blocked by the result of the discussion about the usage/feasibility of the Deconz module of Dresden elektroniks.* - **Kinda solved in this [comment](https://github.com/harpoonhq/home-assistant-project/issues/2#issuecomment-301191072)**

**Subtasks**:

- [x] Setup plain rpi3 (*None*)
- [x] Enable ZigBee support via RaspBee module (#12)
- [x] Configure deconz for headless mode (#16)
- [ ] Try to communicate with Phillips hue light via RaspBee module (#16)
- [ ] Develop custom sofware (HUE Bridge emulator) that makes use of deconz's internal REST-API (#17)
- [ ] Include into Home-Assistant (#13)

**Acceptance criterias**:
- [ ] Acceptance criterias of each subtask need to be met
- [ ] Decisions need to be traceable
- [ ] Proper documentation

**Comment by Wachiwi** [comment]
**Notes**: 

- SPI Communication for ZigBee module
- CPython to make SPI communication viable 
- Double-Check HUE API

**Comment by Wachiwi** [comment]
To get rid of HUE Bridge with the help of the Raspbee module is kinda complicated. Basically there are two possible ways ,a) and b). 

a) Setup the RaspBee module with deconz software in headless mode and write necessary plugins to interface with smart home equipment

b) Rewrite deconz software. Therefore a custom firmware is needed, with the help of the Atmet BitCloud-Stack. The documentation on the framework and custom firmwares themself are very sparse (see [User-Manual 5.2](https://www.dresden-elektronik.de/fileadmin/Downloads/Dokumente/Produkte/ZLL/RaspBee-BHB-en.pdf) and [BitCloud ReadMe](https://www.dresden-elektronik.de/funktechnik/service/download/driver/?L=1&eID=dam_frontend_push&docID=690))

solution a) is the most feasible/preferred solution. This is because b) would be the proper solution but takes to much time and work to realize. So a) is the only solution that is viable. 

Therefor the following actions need to be taken:

- [ ] Rewrite Use-Case
- [ ] Configure deconz for headless mode 
- [ ] Develop custom sofware(HUE Bridge emulator) that makes use of deconz's internal REST-API
- [ ] More to come

**Comment by Wachiwi** [comment]
Further information: 

With the deconz software its only possible to manage lights (no motion sensors etc.). Further it is only possible to handle a maximum of five devices at a time (See attach table from their promotion flyer)

<img width="285" alt="table" src="https://cloud.githubusercontent.com/assets/4199845/26110993/27e8e542-3a54-11e7-93b3-55ba1a7ba6e6.png">

**Comment by Wachiwi** [comment]
unnecessary due to openhab integration.
