### ISSUE TITLE
Homematic support

### ISSUE THREAD

**Issue by tfresh1** [harpoonhq/home-assistant-project#5]
As <STAKEHOLDER> I want to have the possibility ...

**Blockers**:

*None*

**Subtasks**:
- [X] Add switch
- [X] Add socket
- [X] Add motion detection
- [X] Add window shutter
- [X] Add weather station
- [x] Add webbased Homematic manager 
- [ ] Wiki: Add Friendly Names

**Acceptance criterias**:
- [ ] Everything is documented  [wiki](/harpoonhq/home-assistant-project/wiki/Homematic-support)
- [ ] Multiple components where successfully tested by different stakeholders
