### ISSUE TITLE
SSH Welcome Banner

### ISSUE THREAD

**Issue by tfresh1** [harpoonhq/home-assistant-project#6]
As <STAKEHOLDER> I want to have the possibility ...

**Blockers**:

*None*

**Subtasks**:
- [X] change RPI ssh login banner
- [X] add paths to config files
- [X] add ascii art hscoburg logo
- [x] Documentation

**Acceptance criterias**:
- [x]  Everything is documented [wiki](/harpoonhq/home-assistant-project/wiki/Welcome-Banner)
- [x]  Multiple devices where successfully tested by different stakeholders

**Comment by Wachiwi** [comment]
@tfresh1 not reviewable since there is no documentation

**Comment by Wachiwi** [comment]
@shoesch Hint: [hslogo.sh#L9](https://github.com/harpoonhq/home-assistant-project/blob/master/hslogo.sh#L9)

**Comment by tfresh1** [comment]
now you can look at the wiki

**Comment by shoesch** [comment]
@tfresh1: While reviewing I think I found an error in the script (`welcomebanner.sh`) on line 11-13:
```bash
BASEDIR=$(dirname $0)
echo
pr -mtJ hslogo.txt
```

Shouldn't this be like:
```bash
BASEDIR=$(dirname $0)
pr -mtJ $BASEDIR/hslogo.txt
```
